### ISSUE TITLE
Exception in thread during schedule band change

### ISSUE THREAD

**Issue by jshuggins** [jketterl/openwebrx#125] opened 2020-05-27 22:04 UTC
Attached is a portion of the syslog file highlighting some exceptions that are thrown during my scheduled band changes every ten minutes running what I think is the latest experimental version...

            "schedule": {
                "1800-1810": "160m",
                "1810-1820": "80m",
                "1820-1830": "40m",
                "1830-1840": "30m",
                "1840-1850": "20m",
                "1850-1900": "17m",
                "1900-1910": "160m",
                "1910-1920": "80m",
                "1920-1930": "40m",
                "1930-1940": "30m",
                "1940-1950": "20m",
                "1950-2000": "17m",
                "2000-2010": "160m",
                "2010-2020": "80m",
                "2020-2030": "40m",
                "2030-2040": "30m",
                "2040-2050": "20m",
                "2050-2100": "17m",
                "2100-2110": "160m",
                "2110-2120": "80m",
                "2120-2130": "40m",
                "2130-2140": "30m",
                "2140-2150": "20m",
                "2150-2200": "17m",
                "2200-2210": "160m",
                "2210-2220": "80m",
                "2220-2230": "40m",
                "2230-2240": "30m",
                "2240-2250": "20m",
                "2250-2300": "17m",
            },

[syslog.gz](https://github.com/jketterl/openwebrx/files/4692079/syslog.gz)

**Comment by jketterl** [comment] 2020-05-27 22:07
duplicate of #22

**Closed by jketterl** 2020-05-27 22:07 UTC
